# Generated by Django 3.2.4 on 2021-06-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210624_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='have_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.food'),
        ),
        migrations.AlterField(
            model_name='product',
            name='have_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='have_recipe', to='tracker.recipe'),
        ),
    ]
