# Generated by Django 3.2.4 on 2021-06-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_product_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.FloatField(choices=[(10, 10), (100, 100), (150, 150), (200, 200), (250, 250)], verbose_name='Weight of eaten food'),
        ),
    ]
